### ISSUE TITLE
Cloud provides response type change recipe?

### ISSUE THREAD

**Issue by stevenniu9527** [openrewrite/rewrite-openapi#18]
I have tried the existing recipe. Now the recipe MigrateApiOperationToOperation directly deletes the response without change.
```yaml  
- org.openrewrite.java.RemoveAnnotationAttribute:
      annotationType: io.swagger.v3.oas.annotations.Operation
      attributeName: response
```

How to Migrate from Swagger to OpenAPI， Get the replacement below. Especially reserve the reponse type

` @ApiOperation(value = "acquireSyncLeader", notes = "acquireSyncLeader", response = String.class, httpMethod = "GET")`
i hope after migrate :

` @Operation(summary = "acquireSyncLeader", description = "acquireSyncLeader", responses = {@ApiResponse(responseCode = "200",
            content = @Content(schema = @Schema(implementation = String.class))),`
